import ModalManager from "./modal-manager";
import { ButtonParams, Position } from "./interfaces/common";
import { ModalParams, BackDropParams } from "./interfaces/modal";
export default class Modal {
    #private;
    getManager(): ModalManager;
    setManager(manager: ModalManager): void;
    getParams(): Partial<ModalParams>;
    constructor(params?: Partial<ModalParams>);
    getId(): string;
    getBackDropId(): string;
    getModalId(): string;
    getModalHeaderId(): string;
    generateMarginShift(): string;
    isAjaxContentType(): boolean;
    generateAjaxLoaderMarkup(): string;
    generateHtml(): string;
    generateModalMarkup(): string;
    generateXButtonMarkup(): string;
    hasContentError(): boolean;
    generateBodyMarkup(): string;
    generateHeaderMarkup(): string;
    generateFooterMarkup(): string | undefined;
    show(): void;
    setBodyContent(contentType: string | undefined, content: string): void;
    loadHtmlInModalViaFetch(): Promise<void>;
    handleOnBeforeShow(): void;
    handleOnBeforeHide(): void;
    ajaxScriptsAndStylesParsers(html: string): string;
    cleanUpAjaxScriptsAndStyles(): void;
    generateFooterButtonMarkup(button: Partial<ButtonParams>): string;
    handleModalDisplay(modal: HTMLElement | null): void;
    addNoOverflowToBody(): void;
    showAjax(): void;
    showOther(): void;
    hide(callback?: Function | null): void;
    handleModalClose(backDrop?: HTMLElement): void;
    handleFooterOnOk(backDrop?: HTMLElement): void;
    handleOnShow(): void;
    handleDragEvents(): void;
    toggleModalClass(className: string): void;
    addModalClass(className: string): void;
    removeModalClass(className: string): void;
    adjustMargin(position: Position): void;
    setShiftingDistance(distance: Position, adjustMargins?: boolean): void;
    generateBackDropInlineStyles(backDrop?: Partial<BackDropParams>): string;
    isEscKeyDisabled(): boolean;
}
