<?php

    namespace Utility\MarkupGenerators\Html;

    use Examples\Utility\ArrayValue;

    class Select extends Element {

        protected bool $_has_option_group = false;

        protected array $_options = array();

        protected array $_selectedValues = array();

        protected array $_emptyOption = array();

        public function __construct(array $params = array()) {

            parent::__construct($params);

            $this->_params['tagName'] = 'select';

            $attrs = $this->_params['attributes'];

            if(!isset($attrs['size'])) {
                $attrs['size'] = 1;
            } else {
                $attrs['size'] = (int)$attrs['size'];
            }

            $this->_params['attributes'] = $attrs;

            $this->addCssClassIfNotExists('form-control');

            $this->_options = ArrayValue::asArray($this->_params, 'options');

            $this->_selectedValues = ArrayValue::asArray($this->_params, 'selectedValues');

            $this->_emptyOption = ArrayValue::asArray($this->_params, 'emptyOption');

            $this->_has_option_group = ArrayValue::asInt($this->_params, 'has_option_group',0) > 0;

        }

        /**
         * Generate dropdown markup
         *
         * @return string
         */

        public function generate() {

            if(!empty($this->_emptyOption)) {

                $emptyLabel = ArrayValue::asString($this->_emptyOption,'label','~ Select ~');
                $emptyValue = ArrayValue::asString($this->_emptyOption,'value','');

                $this->appendChildElement(Element::create(array(
                    'parent' => $this,
                    'tagName' => 'option',
                    'attributes' => array(
                        'value' => $emptyValue,
                    ),
                    'content' => $emptyLabel
                )));

            }


            if(!empty($this->_options)) {

                if($this->_has_option_group) {

                    foreach ($this->_options as $index => $optGroup) {

                        $label = ArrayValue::asString($optGroup,'label','Option Group '.$index);
                        $data = ArrayValue::asArray($optGroup,'data',[]);

                        $optGroupElem = Element::create(array(
                            'parent' => $this,
                            'tagName' => 'optgroup',
                            'attributes' => array(
                                'label' => $label,
                            ),
                        ));

                        foreach ($data as $optVal => $optLabel) {
                            $optGroupElem->appendChildElement(Element::create(array(
                                'parent' => $optGroupElem,
                                'tagName' => 'option',
                                'attributes' => array(
                                    'value' => $optVal,
                                    'selected' => in_array($optVal, $this->_selectedValues)
                                ),
                                'content' => $optLabel
                            )));
                        }

                        $this->appendChildElement($optGroupElem);

                    }

                } else {
                    foreach ($this->_options as $optVal => $optLabel) {
                        $this->appendChildElement(Element::create(array(
                            'parent' => $this,
                            'tagName' => 'option',
                            'attributes' => array(
                                'value' => $optVal,
                                'selected' => in_array($optVal, $this->_selectedValues)
                            ),
                            'content' => $optLabel
                        )));
                    }
                }



            }


            return parent::generate(); // TODO: Change the autogenerated stub
        }


        /**
         * Creates a dropdown object
         *
         * @param array $params
         *
         * @return Select
         */

        public static function create(array $params = array()) {

            $className = get_called_class();

            return new $className($params);
        }

        /**
         * @return array
         */
        public function getOptions(): array {
            return $this->_options;
        }

        /**
         * @param array $options
         */
        public function setOptions(array $options): void {
            $this->_options = $options;
        }

        /**
         * @return array
         */
        public function getSelectedValues(): array {
            return $this->_selectedValues;
        }

        /**
         * @param array $selected_values
         */
        public function setSelectedValues(array $selected_values): void {
            $this->_selectedValues = $selected_values;
        }

        /**
         * @return array
         */
        public function getEmptyOption(): array {
            return $this->_emptyOption;
        }

        /**
         * Sets empty option
         *
         * @param array $emptyOption
         */
        public function setEmptyOption(array $emptyOption): void {
            $this->_emptyOption = $emptyOption;
        }




    }